### ISSUE TITLE
缺少长按弹出的颜色选项

### ISSUE THREAD

**Issue by tankb52** [fcitx5-android/theme-designer#1]
如题，缺少一个长按弹出时的颜色配置项。

另外建议把打字时的候选词效果加上去，这样 dividerColor 也就有了预览。

**Comment by rocka** [comment]
长按弹出颜色现在有了： `popupBackgroundColor` ，但是没有预览。
选中高亮的文字和背景颜色分别是 `genericActiveForegroundColor` 和 `genericActiveBackgroundColor`
