### ISSUE TITLE
“表情、Unicode和快速输入法”三个按钮同时高亮？

### ISSUE THREAD

**Issue by tankb52** [fcitx5-android/theme-designer#2]
高亮颜色和回车键颜色/accentKeyBackgroundColor 一致。
默认的主题也是如此。
是否是如此设计的？

补充一个截图
![ksnip_20240509-225509](https://github.com/fcitx5-android/theme-designer/assets/10082492/5334d6e7-7824-4b9d-aa3c-d897c4bab80c)

**Comment by rocka** [comment]
设计如此
